name: shokugeki_menu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Design & Icons
  cupertino_icons: ^1.0.8

  # Base de données et Authentification Firebase (100% GRATUIT)
  firebase_core: ^4.10.0
  cloud_firestore: ^6.5.0
  firebase_auth: ^6.5.2
  firebase_storage: ^13.1.0
  firebase_messaging: ^16.1.2

  # Photos & Notifications
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^22.0.0
  shared_preferences: ^2.5.3

  # Localisation & Cartographie (Pour l'adresse à Nouakchott et le livreur)
  google_maps_flutter: ^2.11.0
  geolocator: ^14.0.2
  url_launcher: ^6.3.1

  # Intelligence Artificielle (Moteur officiel Google Gemini pour le Chef IA)
  google_generative_ai: ^0.4.0

  # Réseau & Connexion API (Requis pour l'upload Cloudinary du Directeur)
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Déclaration correcte de tes assets
  assets:
    - assets/images/nagato_avatar.png