name: shokugeki_menu
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ajusté pour garantir la compatibilité maximale des packages récents

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Design & Icons
  cupertino_icons: ^1.0.8

  # Base de données et Authentification Firebase (100% GRATUIT)
  firebase_core: ^4.10.0
  cloud_firestore: ^6.5.0
  firebase_auth: ^6.5.2
  firebase_storage: ^13.1.0
  firebase_messaging: ^16.1.2

  # Photos & Notifications
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^22.0.0
  shared_preferences: ^2.5.3

  # Localisation & Cartographie (Pour l'adresse et le livreur)
  google_maps_flutter: ^2.11.0
  geolocator: ^14.0.2
  url_launcher: ^6.3.1

  # Intelligence Artificielle (Moteur officiel Google Gemini pour le Chef IA)
  google_generative_ai: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# Configuration exclusive pour l'icône de l'application Classe SSSSS
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"

# Specific to Flutter packages.
flutter:
  uses-material-design: true

  # Déclaration des assets de l'application
  assets:
    - assets/icon/logo.png