// ═══════════════════════════════════════════════════════════════
//  MENU PAR DÉFAUT — 40 PLATS — Mauritanie / Afrique de l'Ouest
//  Images gratuites Unsplash CDN (0 MRU)
//  Le directeur peut importer tout ça en 1 clic depuis Firebase.
// ═══════════════════════════════════════════════════════════════

const List<Map<String, dynamic>> kPlatsExempleMauritanie = [

  // ════════════════ BURGERS ════════════════
  {
    'nom': 'Burger Shokugeki Classic',
    'description': 'Double steak haché, fromage fondu, salade, tomate, oignon croustillant et sauce maison.',
    'prix': 280,
    'categorie': 'Burgers',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
  },
  {
    'nom': 'Burger Poulet Crunch',
    'description': 'Blanc de poulet pané croustillant, mayo épicée, cheddar et salade croquante.',
    'prix': 250,
    'categorie': 'Burgers',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1550317138-10000687a72b?w=600&q=80',
  },
  {
    'nom': 'Burger BBQ Inferno',
    'description': 'Steak épais, sauce BBQ fumée, bacon croustillant, jalapeños et oignons caramélisés.',
    'prix': 320,
    'categorie': 'Burgers',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1586816001966-79b736744398?w=600&q=80',
  },
  {
    'nom': 'Burger Végétarien',
    'description': 'Steak de pois chiches maison, avocat, tomate fraîche, roquette et sauce yaourt.',
    'prix': 220,
    'categorie': 'Burgers',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=600&q=80',
  },
  {
    'nom': 'Smash Burger Double',
    'description': 'Deux galettes smashées ultra-croustillantes, double cheddar, cornichons et sauce secrète.',
    'prix': 350,
    'categorie': 'Burgers',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1603064752734-4c48eff3cce6?w=600&q=80',
  },

  // ════════════════ PIZZAS ════════════════
  {
    'nom': 'Pizza Margherita',
    'description': 'Pâte fine croustillante, sauce tomate maison, mozzarella fondante et basilic frais.',
    'prix': 320,
    'categorie': 'Pizzas',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80',
  },
  {
    'nom': 'Pizza Poulet Épicé',
    'description': 'Poulet mariné aux épices, poivrons grillés, oignons rouges, mozzarella et sauce piquante.',
    'prix': 360,
    'categorie': 'Pizzas',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80',
  },
  {
    'nom': 'Pizza 4 Fromages',
    'description': 'Mozzarella, gorgonzola, parmesan, chèvre — une explosion crémeuse inoubliable.',
    'prix': 380,
    'categorie': 'Pizzas',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=600&q=80',
  },
  {
    'nom': 'Pizza Shawarma Fusion',
    'description': 'Viande shawarma, tomates, oignons, sauce blanche et herbes fraîches — fusion Orient-Italie.',
    'prix': 370,
    'categorie': 'Pizzas',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1548369937-47519962c11a?w=600&q=80',
  },

  // ════════════════ POULET ════════════════
  {
    'nom': 'Poulet Crispy Bucket',
    'description': '6 morceaux de poulet panés extra-croustillants, servis avec frites et sauce dip.',
    'prix': 400,
    'categorie': 'Poulet',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1626082927389-6db097a2a282?w=600&q=80',
  },
  {
    'nom': 'Chawarma Poulet',
    'description': 'Escalope de poulet grillée, sauce blanche ail, crudités fraîches, dans du pain pita chaud.',
    'prix': 200,
    'categorie': 'Poulet',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1529006557810-274b0b394c51?w=600&q=80',
  },
  {
    'nom': 'Yassa Poulet',
    'description': 'Poulet mariné citron-oignons, mijoté à la mauritanienne, servi avec riz basmati parfumé.',
    'prix': 300,
    'categorie': 'Poulet',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1598515213692-b6d61ec22da8?w=600&q=80',
  },
  {
    'nom': 'Poulet Grillé + Frites',
    'description': 'Demi-poulet grillé aux herbes, frites maison dorées et sauce barbecue.',
    'prix': 350,
    'categorie': 'Poulet',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1598515213692-b6d61ec22da8?w=600&q=80',
  },
  {
    'nom': 'Ailes Piquantes Buffalo',
    'description': '8 ailes de poulet marinées en sauce buffalo, croustillantes, avec sauce ranch.',
    'prix': 280,
    'categorie': 'Poulet',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=600&q=80',
  },
  {
    'nom': 'Nuggets Maison x10',
    'description': '10 nuggets de poulet 100% naturel, panure croustillante, sauce ketchup maison.',
    'prix': 180,
    'categorie': 'Poulet',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&q=80',
  },

  // ════════════════ PLATS LOCAUX / DIVERS ════════════════
  {
    'nom': 'Thieboudienne Classique',
    'description': 'Riz au poisson sénégalais, légumes du jour, sauce tomate épicée — plat emblématique.',
    'prix': 400,
    'categorie': 'Divers',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1512058564366-43051ee2a136?w=600&q=80',
  },
  {
    'nom': 'Brochettes Méchoui',
    'description': 'Brochettes de viande tendre marinées aux épices mauritaniennes, cuites au charbon de bois.',
    'prix': 350,
    'categorie': 'Divers',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80',
  },
  {
    'nom': 'Méchoui Agneau',
    'description': 'Épaule d\'agneau marinée 24h aux épices du désert, rôtie lentement, fondante à souhait.',
    'prix': 550,
    'categorie': 'Divers',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
  },
  {
    'nom': 'Riz Tacos Mauritanien',
    'description': 'Riz pilaf aux légumes, viande hachée épicée, servi en taco croustillant avec fromage fondu.',
    'prix': 250,
    'categorie': 'Divers',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80',
  },
  {
    'nom': 'Sandwich Kefta',
    'description': 'Galette de kefta épicée, tomates fraîches, frites maison, harissa douce dans du pain baguette.',
    'prix': 180,
    'categorie': 'Divers',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1481070414801-51fd732d7184?w=600&q=80',
  },
  {
    'nom': 'Pasta Bolognaise',
    'description': 'Penne al dente, sauce bolognaise maison mijotée 3h, parmesan râpé et basilic.',
    'prix': 280,
    'categorie': 'Divers',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=600&q=80',
  },
  {
    'nom': 'Wrap Grillé Légumes',
    'description': 'Tortilla grillée garnie de légumes sautés, fromage frais, avocat et sauce coriandre.',
    'prix': 200,
    'categorie': 'Divers',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&q=80',
  },
  {
    'nom': 'Salade César Premium',
    'description': 'Laitue romaine, croûtons grillés, parmesan, poulet grillé et sauce César maison.',
    'prix': 220,
    'categorie': 'Divers',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
  },

  // ════════════════ DESSERTS ════════════════
  {
    'nom': 'Attaya & Pâtisseries',
    'description': 'Thé mauritanien traditionnel en 3 tours, accompagné de pâtisseries au sésame et miel.',
    'prix': 150,
    'categorie': 'Desserts',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80',
  },
  {
    'nom': 'Fondant Chocolat Chaud',
    'description': 'Cœur coulant au chocolat noir 70%, servi avec boule de glace vanille et coulis caramel.',
    'prix': 200,
    'categorie': 'Desserts',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=600&q=80',
  },
  {
    'nom': 'Crêpes Nutella Banane',
    'description': 'Crêpes maison légères, garnies de Nutella généreux, banane fraîche et crème chantilly.',
    'prix': 150,
    'categorie': 'Desserts',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=600&q=80',
  },
  {
    'nom': 'Cheesecake Mangue',
    'description': 'Cheesecake crémeux sur base sablée, coulis de mangue fraîche du Sénégal.',
    'prix': 180,
    'categorie': 'Desserts',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&q=80',
  },
  {
    'nom': 'Baklawa Maison',
    'description': 'Feuilletés croustillants au miel, pistaches et noix — recette de grand-mère.',
    'prix': 120,
    'categorie': 'Desserts',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1530610476181-d83430b64dcd?w=600&q=80',
  },
  {
    'nom': 'Glace 3 Boules',
    'description': 'Vanille, chocolat et fraise — glaces artisanales, garniture au choix.',
    'prix': 100,
    'categorie': 'Desserts',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&q=80',
  },

  // ════════════════ BOISSONS ════════════════
  {
    'nom': 'Jus Bissap Glacé',
    'description': 'Boisson rafraîchissante à base de fleurs d\'hibiscus, légèrement sucrée. 100% naturel.',
    'prix': 100,
    'categorie': 'Boissons',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1546173159-315724a31696?w=600&q=80',
  },
  {
    'nom': 'Jus Bouye (Pain de Singe)',
    'description': 'Jus crémeux de baobab, saveur douce et acidulée, riche en vitamine C.',
    'prix': 100,
    'categorie': 'Boissons',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1614336215203-359e02c35b72?w=600&q=80',
  },
  {
    'nom': 'Smoothie Mangue Passion',
    'description': 'Mangue fraîche, fruit de la passion, lait de coco — 100% fruits mixés.',
    'prix': 150,
    'categorie': 'Boissons',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=600&q=80',
  },
  {
    'nom': 'Citronnade Menthe Fraîche',
    'description': 'Citrons pressés maison, menthe fraîche, sirop naturel et glaçons craquants.',
    'prix': 80,
    'categorie': 'Boissons',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80',
  },
  {
    'nom': 'Milk-Shake Oreo',
    'description': 'Milk-shake épais vanille, biscuits Oreo mixés, crème chantilly généreuse.',
    'prix': 180,
    'categorie': 'Boissons',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&q=80',
  },
  {
    'nom': 'Café Latte Chaud',
    'description': 'Expresso double, mousse de lait onctueuse, touche de cannelle — ambiance café.',
    'prix': 80,
    'categorie': 'Boissons',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1561047029-3000c68339ca?w=600&q=80',
  },
  {
    'nom': 'Eau Minérale',
    'description': 'Bouteille d\'eau minérale fraîche 50cl.',
    'prix': 30,
    'categorie': 'Boissons',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&q=80',
  },
  {
    'nom': 'Soda Canette',
    'description': 'Coca-Cola, Fanta, Sprite — au choix, bien frais.',
    'prix': 50,
    'categorie': 'Boissons',
    'disponible': true,
    'image': 'https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=600&q=80',
  },
];
